version: '3.8'

services:
  server:
    build: ./server
    ports:
      - "4005:4005"
    environment:
      - PORT=4005
      - MONGO_USERNAME=admin
      - MONGO_PASSWORD=project123
      - MONGO_DATABASE=Login
      - MONGO_CLUSTER=cproject.omqqfyp.mongodb.net
    networks:
      - app-network

  client:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - REACT_APP_API_URL=http://server:4005
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
